### PR TITLE
Fix Error

### PR DESCRIPTION
**Pull request by CWZ7605**

### CODE REVIEW

**Comment by DeqingSun** [comment]
Thanks for mentioning this. Did you compile with CH559? 
Please use ```#if defined(CH559)``` for the ```bUD_DP_PD_DIS``` because it does not exist in CH552 or CH549.

**Comment by CWZ7605** [comment]
Well, I'm so busy these days, I will fix it later.

**Comment by DeqingSun** [comment]
@CWZ7605 totally understand, thanks for your contribution

**Comment by DeqingSun** [comment]
@CWZ7605 thank you for mentioning this. Now all examples has been fixed.

**Pull request closed without merging**
